version: "3.9"

services:
  server:
    build: .
    tty: true
    volumes:
      - .:/home/gpt-chatbot
      - bundle_folder:/usr/local/bundle
    environment:
      - API_KEY=<your-api-key>
      - LOG_PATH=/home/gpt-chatbot/logs/server.log

volumes:
  bundle_folder:
